name: Snyk Test with Snyk-Delta Comparison

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk-test-delta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Install system dependencies (jq)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Node.js dependencies for PR branch
        run: npm install

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Install snyk-delta CLI
        run: npm install -g snyk-delta

      - name: Run Snyk Test on PR branch (JSON output)
        run: snyk test --json --print-deps > snyk-current.json || true

      - name: Upload Snyk Current Scan JSON Artifact
        uses: actions/upload-artifact@v3 # Use the upload-artifact action
        with:
          name: snyk-current-scan-json # Name of the artifact
          path: snyk-current.json # Path to the file to upload
          retention-days: 7 # How long to keep the artifact (optional, default is 90 days)

      - name: Run Snyk Test on PR branch (SARIF output for Code Scanning)
        run: |
          snyk test --sarif > snyk-current.sarif || true
          if ! jq empty snyk-current.sarif; then
            echo "SARIF output is invalid or empty. Content:"
            cat snyk-current.sarif
            exit 1
          fi

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-current.sarif

      - name: Fetch main branch and create worktree
        run: |
          git fetch origin main
          git worktree add main-branch origin/main

      - name: Install Node.js dependencies for main branch (baseline)
        working-directory: ./main-branch
        run: npm install

      - name: Run Snyk Test on main (baseline)
        working-directory: ./main-branch
        run: snyk test --json --print-deps > ../snyk-baseline.json || true

      - name: Upload Snyk Baseline Scan JSON Artifact
        uses: actions/upload-artifact@v3 # Use the upload-artifact action
        with:
          name: snyk-baseline-scan-json # Name of the artifact
          path: snyk-baseline.json # Path to the file to upload
          retention-days: 7 # How long to keep the artifact (optional, default is 90 days)

      - name: Compare vulnerabilities using snyk-delta
        run: snyk-delta --base snyk-baseline.json --head snyk-current.json --setPassIfNoBaseline true -d
        # REMOVE "|| true" if you want the job to fail on new issues (snyk-delta exits with 1)
