name: Snyk Test with Snyk-Delta Comparison - Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk-test-delta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Node.js dependencies for PR branch
        run: npm install

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Download snyk-delta CLI binary
        run: |
          curl -L https://github.com/snyk-tech-services/snyk-delta/releases/latest/download/snyk-delta-linux -o snyk-delta
          chmod +x snyk-delta
          sudo mv snyk-delta /usr/local/bin/

      - name: Run Snyk Test on PR branch (multi-project output)
        run: snyk test --all-projects --json > snyk-current.json || true

      - name: Upload Snyk Current Scan JSON
        uses: actions/upload-artifact@v4
        with:
          name: snyk-current-scan-json
          path: snyk-current.json
          retention-days: 7

      - name: Run Snyk Test (SARIF for Code Scanning)
        run: |
          snyk test --sarif > snyk-current.sarif || true
          if ! jq empty snyk-current.sarif; then
            echo "SARIF output is invalid or empty. Content:"
            cat snyk-current.sarif
            exit 1
          fi

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-current.sarif

      - name: Fetch main and create worktree
        run: |
          git fetch origin main
          git worktree add main-branch origin/main

      - name: Install Node.js dependencies for main
        working-directory: ./main-branch
        run: npm install

      - name: Run Snyk Test on main (baseline)
        working-directory: ./main-branch
        run: snyk test --all-projects --json > ../snyk-baseline.json || true

      - name: Upload Snyk Baseline Scan JSON
        uses: actions/upload-artifact@v4
        with:
          name: snyk-baseline-scan-json
          path: snyk-baseline.json
          retention-days: 7

      # ✅ Download both JSONs for local inspection (optional)
      - name: Download JSON artifacts for debug
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      # ✅ Debug view before snyk-delta
      - name: Inspect JSON before snyk-delta
        run: |
          echo "✅ snyk-current.json:"
          cat ./artifacts/snyk-current-scan-json/snyk-current.json | jq .
          echo "✅ snyk-baseline.json:"
          cat ./artifacts/snyk-baseline-scan-json/snyk-baseline.json | jq .

      # ✅ Run snyk-delta comparison
      - name: Compare vulnerabilities using snyk-delta
        run: snyk-delta --base ./artifacts/snyk-baseline-scan-json/snyk-baseline.json --head ./artifacts/snyk-current-scan-json/snyk-current.json --setPassIfNoBaseline true -d
