name: snyk test with snyk-delta

on:
  #pull_request:
  workflow_dispatch:

jobs:
  snyk-test-delta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Install node.js dependencies
        run: npm install

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Install snyk-delta
        run: npm install -g snyk-delta
        
      # Run Snyk Test on PR branch, save JSON
      - name: Run Snyk Test (JSON)
        run: snyk test --json > snyk-current.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      # Upload SARIF for UI (optional)
      - name: Run Snyk Test (SARIF)
        run: snyk test --sarif > snyk-current.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-current.sarif
          
      # Fetch baseline (main branch)
      - name: Fetch main branch
        run: |
          git fetch origin main --depth=1
          git checkout origin/main

      - name: Run Snyk Test on main branch
        run: snyk test --json > snyk-baseline.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}     

      - name: print current json
        run:  cat snyk-baseline.json | jq .
          
      - name: print baseline json
        run: cat snyk-current.json | jq .

          # Use snyk-delta to detect new issues
      - name: Compare with snyk-delta
        run:  snyk-delta --base snyk-baseline.json --head snyk-current.json -d
