name: snyk test with snyk-delta

on:
  # pull_request:
  workflow_dispatch:

env:
    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk-test-delta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          npm install

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Install snyk-delta
        run: npm install -g snyk-delta

      - name: Run Snyk Test on PR branch (JSON)
        run: snyk test --json > snyk-current.json || true        

      - name: Run Snyk Test on PR branch (SARIF)
        run: |
          snyk test --sarif > snyk-current.sarif || true
          if ! jq empty snyk-current.sarif; then
            echo "SARIF output is invalid"; cat snyk-current.sarif; exit 1
          fi        

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-current.sarif

      - name: Fetch main and create worktree
        run: |
          git fetch origin main
          git worktree add main-branch origin/main

      - name: Run Snyk Test on main (baseline)
        working-directory: ./main-branch
        run: snyk test --json > ../snyk-baseline.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Print current branch JSON
        run: cat snyk-current.json | jq .

      - name: Print main branch baseline JSON
        run: cat snyk-baseline.json | jq .

      - name: Compare vulnerabilities using snyk-delta
        run: snyk-delta --base snyk-baseline.json --head snyk-current.json --setPassIfNoBaseline true -d

